//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_PP.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выполнение_работ
    {
        public int ID { get; set; }
        public Nullable<int> ID_Сотрудник { get; set; }
        public string НаименованиеРаботы { get; set; }
        public Nullable<System.DateTime> ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаОкончания { get; set; }
        public Nullable<System.DateTime> КрайнийСрокСдачи { get; set; }
        public Nullable<int> ID_СтатусРаботы { get; set; }
    
        public virtual Работник Работник { get; set; }
        public virtual СтатусРаботы СтатусРаботы { get; set; }
    }
}
