//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_PP.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование
    {
        public string Номер { get; set; }
        public string Наименование { get; set; }
        public string Количество { get; set; }
        public Nullable<System.DateTime> ДатаВнесения { get; set; }
        public Nullable<System.DateTime> ДатаСписания { get; set; }
        public Nullable<int> ID_Единица { get; set; }
        public Nullable<int> ID_Расположение { get; set; }
        public Nullable<int> ID_Статус { get; set; }
    
        public virtual Единицы Единицы { get; set; }
        public virtual Кабинеты Кабинеты { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
